// Superposition Network Switcher Hook
// Generated by Cradle - https://cradle-web-eight.vercel.app

'use client';

import { useCallback, useMemo } from 'react';
import { useChainId, useSwitchChain } from 'wagmi';
import { superpositionMainnet, superpositionTestnet } from '../lib/chains';

export type SuperpositionNetwork = 'mainnet' | 'testnet';

/**
 * Hook for managing Superposition network switching
 */
export function useSuperpositionNetwork() {
  const chainId = useChainId();
  const { switchChain, isPending, error } = useSwitchChain();

  const currentNetwork = useMemo((): SuperpositionNetwork | null => {
    if (chainId === 55244) return 'mainnet';
    if (chainId === 98985) return 'testnet';
    return null;
  }, [chainId]);

  const isOnSuperposition = currentNetwork !== null;

  const switchToSuperposition = useCallback(
    async (network: SuperpositionNetwork = 'mainnet') => {
      const targetChain = network === 'mainnet' 
        ? superpositionMainnet 
        : superpositionTestnet;
      
      await switchChain({ chainId: targetChain.id });
    },
    [switchChain]
  );

  const switchNetwork = useCallback(
    async (network: SuperpositionNetwork) => {
      await switchToSuperposition(network);
    },
    [switchToSuperposition]
  );

  return {
    currentNetwork,
    isOnSuperposition,
    isSwitching: isPending,
    switchError: error,
    switchToSuperposition,
    switchNetwork,
    chainId,
  };
}

/**
 * Get explorer URL for a transaction
 */
export function getSuperpositionExplorerUrl(
  txHash: string,
  network: SuperpositionNetwork = 'mainnet'
): string {
  const baseUrl = network === 'mainnet'
    ? 'https://explorer.superposition.so'
    : 'https://testnet-explorer.superposition.so';
  return `${baseUrl}/tx/${txHash}`;
}

/**
 * Get explorer URL for an address
 */
export function getSuperpositionAddressUrl(
  address: string,
  network: SuperpositionNetwork = 'mainnet'
): string {
  const baseUrl = network === 'mainnet'
    ? 'https://explorer.superposition.so'
    : 'https://testnet-explorer.superposition.so';
  return `${baseUrl}/address/${address}`;
}