// Superposition Contract Addresses and Constants
// Generated by Cradle - https://cradle-web-eight.vercel.app
// Contract addresses verified from official Superposition documentation

import type { Address } from 'viem';

/**
 * Superposition Mainnet Contract Addresses (Chain ID: 55244)
 * Source: https://docs.long.so/ and https://docs.superposition.so/
 */
export const SUPERPOSITION_MAINNET_CONTRACTS = {
  // Longtail AMM contracts (verified from docs.long.so)
  LONGTAIL_AMM: '0xF3334049A3ce7e890bd4f8C6a0FBC70e38fd3746' as Address,
  LONGTAIL_NFT_MANAGER: '0xdD193817F66276d1EAd064dF8F3112b553A50d10' as Address,
  LONGTAIL_POSITION_HANDLER: '0x1aC593E976bD676Aa9609677AB41d52436e40260' as Address,
  LONGTAIL_PERMIT2_ROUTER: '0x244517Dc59943E8CdFbD424Bdb3262c5f04a1387' as Address,
  LEO_PROXY: '0xC5a5bB74e41A01927d29dbffA8Ab796c784bCBA8' as Address,
  
  // Common tokens (verified from docs.long.so)
  USDC: '0x6c030c5CC283F791B26816f325b9C632d964F8A1' as Address, // fUSDC/base asset
  WETH: '0x1fB719f10b56d7a85DCD32f27f897375fB21cfdd' as Address,
  ARB: '0xA2555701754464d32D9624149E3fDb459F3c8DE4' as Address,
  FLY: '0x80eFAD50D395671C13C4b1FA2969f7a7Aa9EF7b3' as Address,
  
  // Super Assets (yield-bearing wrappers)
  // TODO: Super Asset wrapping contracts not publicly documented yet
  // See https://docs.superposition.so/superposition-mainnet/super-layer/super-assets
  SUPER_USDC: '0x0000000000000000000000000000000000000000' as Address, // sUSDC wrapper
  SUPER_ETH: '0x0000000000000000000000000000000000000000' as Address, // sETH wrapper
  SUPER_WETH: '0x0000000000000000000000000000000000000000' as Address, // sWETH wrapper
  
  // Utility Mining / TRF
  // TODO: TRF contracts not publicly documented yet
  // See https://docs.superposition.so/superposition-mainnet/super-layer/utility-mining
  UTILITY_MINING: '0x0000000000000000000000000000000000000000' as Address,
} as const;


/**
 * Superposition Testnet Contract Addresses (Chain ID: 98985)
 * Source: https://docs.long.so/ and https://docs.superposition.so/
 */
export const SUPERPOSITION_TESTNET_CONTRACTS = {
  // Longtail AMM contracts (verified from docs.long.so)
  LONGTAIL_AMM: '0xAe86141e3f1C9168cE6c948FDC884F2A5f45d7B6' as Address,
  LONGTAIL_NFT_MANAGER: '0x8aa3750A7e8c98830e3421a89bFf80Fc175e4C98' as Address,
  LONGTAIL_POSITION_HANDLER: '0x73387E7E4DF41f58Be13cdE4Dd4EAf3675c1C44c' as Address,
  LONGTAIL_PERMIT2_ROUTER: '0x2246431582087b930F2CE561c34deb8E7e5c44bE' as Address,
  LEO: '0xADA1629b77A4864340b7b9Dc4B9874068E844b08' as Address,
  
  // Test tokens (verified from docs.long.so)
  FUSDC: '0xA8EA92c819463EFbEdDFB670FEfC881A480f0115' as Address, // Testnet fUSDC
  WETH: '0xde104342B32BCa03ec995f999181f7Cf1fFc04d7' as Address,
  USDC: '0x6437fdc89cED41941b97A9f1f8992D88718C81c5' as Address,
  WRAPPED_SPN: '0x22b9fa698b68bBA071B513959794E9a47d19214c' as Address, // wSPN
  CATBUX: '0x36c116a8851869cf8a99b3Bda0Fad42453D32B99' as Address, // CAT token
  
  // Faucet (verified from Superposition docs)
  FAUCET: '0xD1919257706d044f5c218142110431885792bc2B' as Address,
} as const;


/**
 * Get contracts for a specific chain ID
 */
export function getSuperpositionContracts(chainId: number) {
  switch (chainId) {
    case 55244:
      return SUPERPOSITION_MAINNET_CONTRACTS;
    case 98985:
      return SUPERPOSITION_TESTNET_CONTRACTS;
    default:
      throw new Error(`Unknown Superposition chain ID: ${chainId}`);
  }
}

/**
 * Network configuration
 */
export const SUPERPOSITION_CONFIG = {
  mainnet: {
    chainId: 55244,
    name: 'Superposition',
    rpcUrl: 'https://rpc.superposition.so',
    wsUrl: 'wss://rpc.superposition.so',
    explorerUrl: 'https://explorer.superposition.so',
    bridgeUrl: 'https://bridge.superposition.so',
    dexUrl: 'https://long.so',
  },
  testnet: {
    chainId: 98985,
    name: 'Superposition Testnet',
    rpcUrl: 'https://testnet-rpc.superposition.so',
    wsUrl: 'wss://testnet-rpc.superposition.so',
    explorerUrl: 'https://testnet-explorer.superposition.so',
    bridgeUrl: 'https://bridge.superposition.so',
    faucetUrl: 'https://faucet.superposition.so',
  },
} as const;