// Superposition Wagmi Configuration
// Generated by Cradle - https://cradle-web-eight.vercel.app

import { http, webSocket } from 'wagmi';
import { superpositionMainnet, superpositionTestnet } from './chains';

/**
 * Superposition chain transports for wagmi
 */
export const superpositionTransports = {
  [superpositionMainnet.id]: webSocket('wss://rpc.superposition.so'),
  [superpositionTestnet.id]: webSocket('wss://testnet-rpc.superposition.so'),
} as const;

/**
 * All Superposition chains for wagmi config
 */
export const superpositionChainsConfig = [
  superpositionMainnet,
  superpositionTestnet,
] as const;

/**
 * Example wagmi config integration:
 * 
 * import { createConfig } from 'wagmi';
 * import { superpositionChainsConfig, superpositionTransports } from './superposition';
 * 
 * const config = createConfig({
 *   chains: [...otherChains, ...superpositionChainsConfig],
 *   transports: {
 *     ...otherTransports,
 *     ...superpositionTransports,
 *   },
 * });
 */